"""Mapping between Excel school names (First Year Class file) and LSD CSV slugs.

Every entry maps an Excel SchoolName -> the corresponding LSD file slug (without .csv).
Schools with no LSD data map to None.
"""

# Excel SchoolName -> LSD slug (or None if no LSD data exists)
EXCEL_TO_LSD = {
    "Akron, The University of": "university_of_akron_school_of_law",
    "Alabama, The University of": "university_of_alabama_law_school",
    "Albany Law School": "albany_law_school",
    "American University": "american_university_law_school",
    "Appalachian School of Law": "appalachian_school_of_law",
    "Arizona State University": "asu_law",
    "Arizona, The University of": "university_of_arizona_law_school",
    "Arkansas at Little Rock, University of": "ualr_william_h_bowen_school_of_law",
    "Arkansas, University of": "university_of_arkansas_law_school",
    "Atlanta's John Marshall Law School": "john_marshall_law_school",
    "Ave Maria School of Law": "ave_maria_university",
    "Baltimore, University of": "university_of_baltimore_law_school",
    "Barry University": "barry_university_school_of_law",
    "Baylor University": "baylor_law_school",
    "Belmont University": "belmont_university_college_of_law",
    "Boston College": "boston_college_law_school",
    "Boston University": "boston_university_law_school",
    "Brigham Young University": "byu_law_school",
    "Brooklyn Law School": "brooklyn_law_school",
    "Buffalo, University at": "university_at_buffalo_law_school",
    "California Western School of Law": "california_western_school_of_law",
    "California-Berkeley, University of": "uc_berkeley_law_school",
    "California-Davis, University of": "uc_davis_law_school",
    "California-Irvine, University of": "uc_irvine_law",
    "California-Los Angeles, University of": "ucla_law",
    "California-San Francisco, University of": "uc_law_san_francisco",
    "Campbell University": "campbell_law_school",
    "Capital University Law School": "capital_university_law_school",
    "Cardozo, Yeshiva University": "cardozo_school_of_law",
    "Case Western Reserve University": "case_western_reserve_university_school_of_law",
    "Catholic University of America, The": "columbus_school_of_law_the_catholic_university_of_america",
    "Chapman University": "chapman_university_fowler_school_of_law",
    "Charleston School of Law": "charleston_school_of_law",
    "Chicago, The University of": "university_of_chicago_law_school",
    "Chicago-Kent, Illinois Institute of Technology": "chicago_kent_law_school",
    "Cincinnati, University of": "university_of_cincinnati_law_school",
    "City University of New York, University of": "cuny_law_school",
    "Cleveland State University": "cleveland_marshall_college_of_law",
    "Colorado, University of": "colorado_law",
    "Columbia University": "columbia_law_school",
    "Connecticut, University of": "uconn_law_school",
    "Cooley Law School": "cooley_law_school",
    "Cornell University": "cornell_law_school",
    "Creighton University": "creighton_university_school_of_law",
    "Dayton, University of": "university_of_dayton_school_of_law",
    "DePaul University": "depaul_law_school",
    "Denver, University of": "denver_law_school",
    "Detroit Mercy, University of": "detroit_mercy_law",
    "District of Columbia, University of": "udc_david_a_clarke_school_of_law",
    "Drake University": "drake_law_school",
    "Drexel University": "drexel_university_thomas_r_kline_school_of_law",
    "Duke University": "duke_law",
    "Duquesne University": "duquesne_law_school",
    "Elon University": "elon_university_school_of_law",
    "Emory University": "emory_law_school",
    "Faulkner University": "cumberland_school_of_law",
    "Florida A&M University": "famu_law_school",
    "Florida International University": "fiu_law_school",
    "Florida State University": "fsu_law",
    "Florida, University of": "uf_law_school",
    "Fordham University": "fordham_law_school",
    "George Mason University": "antonin_scalia_law_school",
    "George Washington University, The": "gw_law_school",
    "Georgetown University": "georgetown_law",
    "Georgia State University": "georgia_state_law_school",
    "Georgia, University of": "uga_law_school",
    "Gonzaga University": "gonzaga_university_school_of_law",
    "Harvard University": "harvard_law_school",
    "Hawaii, University of": "university_of_hawaii_at_manoa_william_s_richardson_school_of_law",
    "Hofstra University": "hofstra_law_school",
    "Houston, University of": "university_of_houston_law_school",
    "Howard University": "howard_law_school",
    "Idaho, University of": "university_of_idaho_college_of_law",
    "Illinois, University of": "university_of_illinois_college_of_law",
    "Illinois-Chicago, University of": "university_of_illinois_chicago_school_of_law",
    "Indiana University-Bloomington": "maurer_law_school",
    "Indiana University-Indianapolis": "mckinney_law_school",
    "Inter American University of Puerto Rico": None,
    "Iowa, University of": "iowa_law",
    "Jacksonville University": None,
    "Kansas, The University of": "ku_school_of_law",
    "Kentucky, University of": "uk_law_school",
    "Lewis & Clark Law School": "lewis_and_clark_law_school",
    "Liberty University": "liberty_university_school_of_law",
    "Lincoln Memorial University": "lincoln_memorial_university_duncan_school_of_law",
    "Louisiana State University": "lsu_law_school",
    "Louisville, University of": "brandeis_school_of_law",
    "Loyola Marymount University-Los Angeles": "loyola_law_school_los_angeles",
    "Loyola University-Chicago": "loyola_law_school_chicago",
    "Loyola University-New Orleans": "loyola_university_law_school_nola",
    "Maine, University of": "university_of_maine_law_school",
    "Marquette University": "marquette_university_law_school",
    "Maryland, University of": "umd_law_school",
    "Massachusetts/Dartmouth, University of": "umass_law",
    "Memphis, The University of": "cecil_c_humphreys_school_of_law",
    "Mercer University": "mercer_university_walter_f_george_school_of_law",
    "Miami, University of": "university_of_miami_school_of_law",
    "Michigan State University": "michigan_state_law_school",
    "Michigan, University of": "michigan_law_school",
    "Minnesota, University of": "university_of_minnesota_law_school",
    "Mississippi College": "mississippi_college_school_of_law",
    "Mississippi, The University of": "ole_miss_law_school",
    "Missouri, University of": "mizzou_law_school",
    "Missouri-Kansas City, University of": "umkc_school_of_law",
    "Mitchell/Hamline School of Law": "mitchell_hamline_school_of_law",
    "Montana, University of": "university_of_montana_law_school",
    "Nebraska, University of": "university_of_nebraska_law_school",
    "Nevada-Las Vegas, University of": "william_s_boyd_school_of_law_at_unlv",
    "New England Law/Boston": "new_england_law_boston",
    "New Hampshire, University of": "unh_law_school",
    "New Mexico, The University of": "unm_law_school",
    "New York Law School": "new_york_law_school",
    "New York University": "nyu_law_school",
    "North Carolina Central University": "nccu_school_of_law",
    "North Carolina, University of": "unc_law_school",
    "North Dakota, University of": "und_law_school",
    "North Texas at Dallas, University of": "unt_dallas_college_of_law",
    "Northeastern University": "northeastern_law_school",
    "Northern Illinois University": "northern_illinois_university_law_school",
    "Northern Kentucky University": "salmon_p_chase_law_school",
    "Northwestern University": "northwestern_law_school",
    "Notre Dame, University of": "notre_dame_law_school",
    "Nova Southeastern University": "nsu_shepard_broad_college_of_law",
    "Ohio Northern University": "ohio_northern_law_school",
    # "Ohio State University, The" — removed; Excel uses "The Ohio State University"
    "Oklahoma City University": "oklahoma_city_law_school",
    "Oklahoma, University of": "university_of_oklahoma_law_school",
    "Oregon, University of": "university_of_oregon_school_of_law",
    "Pace University": "pace_law_school",
    "Pacific, University of the": "pacific_mcgeorge_school_of_law",
    "Penn State Dickinson Law": "penn_state_law_school_dickinson",
    "Penn State University Park": "penn_state_law_school",
    "Pennsylvania, University of": "penn_law",
    "Pepperdine University": "pepperdine_law_school",
    "Pittsburgh, University of": "university_of_pittsburgh_law_school",
    "Pontifical Catholic University of Puerto Rico": None,
    "Puerto Rico, University of": None,
    "Quinnipiac University": "quinnipiac_law_school",
    "Regent University": "regent_university_school_of_law",
    "Richmond, University of": "university_of_richmond_school_of_law",
    "Roger Williams University": "roger_williams_university_school_of_law",
    "Rutgers University": "rutgers_law_school_newark_campus",
    "Saint Louis University": "saint_louis_university_law_school",
    "Samford University": "cumberland_school_of_law",
    "San Diego, University of": "usd_law_school",
    "San Francisco, University of": "usf_law_school",
    "Santa Clara University": "santa_clara_university_school_of_law",
    "Seattle University": "seattle_university_law_school",
    "Seton Hall University": "seton_hall_law_school",
    "South Carolina, University of": "university_of_south_carolina_school_of_law",
    "South Dakota, University of": "university_of_south_dakota_law_school",
    "South Texas College of Law Houston": "south_texas_college_of_law_houston",
    "Southern California, University of": "usc_gould_school_of_law",
    "Southern Illinois University": "siu_school_of_law",
    "Southern Methodist University": "smu_dedman_school_of_law",
    "Southern University": "southern_university_law_center",
    "Southwestern Law School": "southwestern_law_school",
    "St. John's University": "st_johns_law_school",
    "St. Mary's University": "st_marys_university_school_of_law",
    "St. Thomas University (Miami)": "st_thomas_law_school",
    "St. Thomas, (Minneapolis) University of": "university_of_st_thomas_school_of_law",
    "Stanford University": "stanford_law_school",
    "Stetson University": "stetson_law_school",
    "Suffolk University": "suffolk_law_school",
    "Syracuse University": "syracuse_law_school",
    "Temple University": "temple_law_school",
    "Tennessee, University of": "university_of_tennessee_law_school",
    "Texas A&M University": "texas_am_law_school",
    "Texas Southern University": "thurgood_marshall_school_of_law",
    "Texas Tech University": "texas_tech_law_school",
    "Texas, University of": "ut_austin_law_school",
    "The Ohio State University": "moritz_college_of_law",
    "Toledo, The University of": "university_of_toledo_law_school",
    "Touro University": "touro_law_school",
    "Tulane University": "tulane_law_school",
    "Tulsa, The University of": "the_university_of_tulsa_college_of_law",
    "Utah, The University of": "university_of_utah_law_school",
    "Vanderbilt University": "vanderbilt_law_school",
    "Vermont Law School": "vermont_law_school",
    "Villanova University": "villanova_law_school",
    "Virginia, University of": "uva_law_school",
    "Wake Forest University": "wake_forest_law_school",
    "Washburn University": "washburn_university_school_of_law",
    "Washington and Lee University": "washington_and_lee_law_school",
    "Washington University (St. Louis)": "washington_university_school_of_law",
    "Washington, University of": "university_of_washington_law_school",
    "Wayne State University": "wayne_state_university_law_school",
    "West Virginia University": "wvu_college_of_law",
    "Western New England University": "western_new_england_law_school",
    "Western State, Westcliff University": "western_state_college_of_law",
    "Widener University Commonwealth Law School": "widener_law_school",
    "Widener University Delaware Law School": "widener_law_school",
    "Willamette University": "willamette_university_college_of_law",
    "William & Mary": "william_and_mary_law_school",
    "Wilmington University School of Law": None,
    "Wisconsin, University of": "wisconsin_law_school",
    "Wyoming, University of": "university_of_wyoming_law_school",
    "Yale University": "yale_law_school",
}

# Reverse lookup: LSD slug -> Excel name (first match wins)
LSD_TO_EXCEL = {}
for excel_name, slug in EXCEL_TO_LSD.items():
    if slug and slug not in LSD_TO_EXCEL:
        LSD_TO_EXCEL[slug] = excel_name


# Common nicknames/abbreviations -> Excel SchoolName
NICKNAMES = {
    "yale": "Yale University",
    "stanford": "Stanford University",
    "harvard": "Harvard University",
    "columbia": "Columbia University",
    "chicago": "Chicago, The University of",
    "uchicago": "Chicago, The University of",
    "nyu": "New York University",
    "penn": "Pennsylvania, University of",
    "upenn": "Pennsylvania, University of",
    "uva": "Virginia, University of",
    "virginia": "Virginia, University of",
    "berkeley": "California-Berkeley, University of",
    "ucberkeley": "California-Berkeley, University of",
    "uc berkeley": "California-Berkeley, University of",
    "michigan": "Michigan, University of",
    "umich": "Michigan, University of",
    "duke": "Duke University",
    "northwestern": "Northwestern University",
    "cornell": "Cornell University",
    "georgetown": "Georgetown University",
    "ucla": "California-Los Angeles, University of",
    "usc": "Southern California, University of",
    "vanderbilt": "Vanderbilt University",
    "wustl": "Washington University (St. Louis)",
    "washu": "Washington University (St. Louis)",
    "washington university": "Washington University (St. Louis)",
    "notre dame": "Notre Dame, University of",
    "ndls": "Notre Dame, University of",
    "emory": "Emory University",
    "gw": "George Washington University, The",
    "george washington": "George Washington University, The",
    "bu": "Boston University",
    "boston university": "Boston University",
    "bc": "Boston College",
    "boston college": "Boston College",
    "fordham": "Fordham University",
    "uf": "Florida, University of",
    "ufl": "Florida, University of",
    "florida": "Florida, University of",
    "fsu": "Florida State University",
    "fiu": "Florida International University",
    "um": "Miami, University of",
    "umiami": "Miami, University of",
    "miami": "Miami, University of",
    "texas": "Texas, University of",
    "ut austin": "Texas, University of",
    "texas a&m": "Texas A&M University",
    "texas am": "Texas A&M University",
    "houston": "Houston, University of",
    "smu": "Southern Methodist University",
    "colorado": "Colorado, University of",
    "denver": "Denver, University of",
    "drexel": "Drexel University",
    "temple": "Temple University",
    "villanova": "Villanova University",
    "maryland": "Maryland, University of",
    "umd": "Maryland, University of",
    "american": "American University",
    "brooklyn": "Brooklyn Law School",
    "cardozo": "Cardozo, Yeshiva University",
    "washington": "Washington, University of",
    "uw": "Washington, University of",
    "minnesota": "Minnesota, University of",
    "wisconsin": "Wisconsin, University of",
    "iowa": "Iowa, University of",
    "illinois": "Illinois, University of",
    "ohio state": "The Ohio State University",
    "osu": "The Ohio State University",
    "georgia": "Georgia, University of",
    "uga": "Georgia, University of",
    "alabama": "Alabama, The University of",
    "tennessee": "Tennessee, University of",
    "kentucky": "Kentucky, University of",
    "wake forest": "Wake Forest University",
    "unc": "North Carolina, University of",
    "north carolina": "North Carolina, University of",
    "george mason": "George Mason University",
    "gmu": "George Mason University",
    "richmond": "Richmond, University of",
    "william mary": "William & Mary",
    "william and mary": "William & Mary",
    "w&m": "William & Mary",
    "tulane": "Tulane University",
    "pepperdine": "Pepperdine University",
    "uc irvine": "California-Irvine, University of",
    "uci": "California-Irvine, University of",
    "uc davis": "California-Davis, University of",
    "uc hastings": "California-San Francisco, University of",
    "uc sf": "California-San Francisco, University of",
    "hastings": "California-San Francisco, University of",
    "lsu": "Louisiana State University",
    "case western": "Case Western Reserve University",
    "seton hall": "Seton Hall University",
    "rutgers": "Rutgers University",
    "st johns": "St. John's University",
    "saint thomas university": "St. Thomas University (Miami)",
    "saint thomas": "St. Thomas University (Miami)",
    "suffolk": "Suffolk University",
    "northeastern": "Northeastern University",
    "hofstra": "Hofstra University",
    "nova": "Nova Southeastern University",
    "howard": "Howard University",
    "baylor": "Baylor University",
    "arizona state": "Arizona State University",
    "asu": "Arizona State University",
    "arizona": "Arizona, The University of",
    "oregon": "Oregon, University of",
    "pittsburgh": "Pittsburgh, University of",
    "pitt": "Pittsburgh, University of",
    "marquette": "Marquette University",
    "loyola la": "Loyola Marymount University-Los Angeles",
    "loyola los angeles": "Loyola Marymount University-Los Angeles",
    "loyola chicago": "Loyola University-Chicago",
    "creighton": "Creighton University",
    "syracuse": "Syracuse University",
    "connecticut": "Connecticut, University of",
    "uconn": "Connecticut, University of",
    "depaul": "DePaul University",
    "lewis clark": "Lewis & Clark Law School",
    "lewis and clark": "Lewis & Clark Law School",
    "santa clara": "Santa Clara University",
    "san diego": "San Diego, University of",
    "san francisco": "San Francisco, University of",
    "buffalo": "Buffalo, University at",
    "maine": "Maine, University of",
    "vermont": "Vermont Law School",
    "new hampshire": "New Hampshire, University of",
    "hawaii": "Hawaii, University of",
    "idaho": "Idaho, University of",
    "montana": "Montana, University of",
    "wyoming": "Wyoming, University of",
    "nebraska": "Nebraska, University of",
    "oklahoma": "Oklahoma, University of",
    "arkansas": "Arkansas, University of",
    "mississippi": "Mississippi, The University of",
    "ole miss": "Mississippi, The University of",
    "south carolina": "South Carolina, University of",
    "cincinnati": "Cincinnati, University of",
    "dayton": "Dayton, University of",
    "akron": "Akron, The University of",
    "toledo": "Toledo, The University of",
    "penn state": "Penn State University Park",
    "campbell": "Campbell University",
    "chapman": "Chapman University",
    "elon": "Elon University",
    "pace": "Pace University",
    "seattle": "Seattle University",
    "gonzaga": "Gonzaga University",
    "drake": "Drake University",
    "duquesne": "Duquesne University",
    "usc ed": "Southern California, University of",
}


def _normalize(name: str) -> str:
    return "".join(ch for ch in name.lower() if ch.isalnum())


# Build normalized lookup for flexible input matching
_NORM_EXCEL = {_normalize(k): k for k in EXCEL_TO_LSD}
_NORM_LSD = {_normalize(slug.replace("_", " ")): slug
             for slug in set(EXCEL_TO_LSD.values()) if slug}
_NORM_NICK = {_normalize(k): v for k, v in NICKNAMES.items()}


def resolve_school(user_input: str):
    """Given a user-typed school name, return (excel_name, lsd_slug) or None.

    Tries exact match, nickname lookup, normalized match against Excel names,
    and normalized match against LSD slugs. Returns None if nothing matches.
    """
    # Exact Excel name
    if user_input in EXCEL_TO_LSD:
        return user_input, EXCEL_TO_LSD[user_input]

    key = _normalize(user_input)

    # Nickname lookup
    if key in _NORM_NICK:
        excel = _NORM_NICK[key]
        return excel, EXCEL_TO_LSD.get(excel)

    # Normalized Excel name match
    if key in _NORM_EXCEL:
        excel = _NORM_EXCEL[key]
        return excel, EXCEL_TO_LSD[excel]

    # Normalized LSD slug match
    if key in _NORM_LSD:
        slug = _NORM_LSD[key]
        excel = LSD_TO_EXCEL.get(slug)
        return excel, slug

    return None


# ── School rankings (US News 2025) ──────────────────────────────────
# Keyed by Excel SchoolName -> integer rank.  Ties share the same number.
# Parsed from schoolrank.xlsx with manual overrides for name mismatches.

SCHOOL_RANK = {
    "Akron, The University of": 144,
    "Alabama, The University of": 34,
    "Albany Law School": 121,
    "American University": 54,
    "Appalachian School of Law": 190,
    "Arizona State University": 34,
    "Arizona, The University of": 41,
    "Arkansas at Little Rock, University of": 121,
    "Arkansas, University of": 85,
    "Atlanta's John Marshall Law School": 171,
    "Ave Maria School of Law": 190,
    "Baltimore, University of": 103,
    "Barry University": 190,
    "Baylor University": 85,
    "Belmont University": 162,
    "Boston College": 30,
    "Boston University": 22,
    "Brigham Young University": 51,
    "Brooklyn Law School": 76,
    "Buffalo, University at": 112,
    "California Western School of Law": 171,
    "California-Berkeley, University of": 6,
    "California-Davis, University of": 22,
    "California-Irvine, University of": 25,
    "California-Los Angeles, University of": 12,
    "California-San Francisco, University of": 46,
    "Campbell University": 171,
    "Capital University Law School": 180,
    "Cardozo, Yeshiva University": 54,
    "Case Western Reserve University": 70,
    "Catholic University of America, The": 103,
    "Chapman University": 162,
    "Charleston School of Law": 184,
    "Chicago, The University of": 3,
    "Chicago-Kent, Illinois Institute of Technology": 85,
    "Cincinnati, University of": 103,
    "City University of New York, University of": 103,
    "Cleveland State University": 138,
    "Colorado, University of": 34,
    "Columbia University": 4,
    "Connecticut, University of": 51,
    "Cooley Law School": 190,
    "Cornell University": 12,
    "Creighton University": 121,
    "Dayton, University of": 144,
    "DePaul University": 97,
    "Denver, University of": 54,
    "Detroit Mercy, University of": 144,
    "District of Columbia, University of": 154,
    "Drake University": 121,
    "Drexel University": 97,
    "Duke University": 9,
    "Duquesne University": 138,
    "Elon University": 144,
    "Emory University": 22,
    "Faulkner University": 190,
    "Florida A&M University": 162,
    "Florida International University": 112,
    "Florida State University": 46,
    "Florida, University of": 30,
    "Fordham University": 34,
    "George Mason University": 70,
    "George Washington University, The": 25,
    "Georgetown University": 12,
    "Georgia State University": 54,
    "Georgia, University of": 25,
    "Gonzaga University": 103,
    "Harvard University": 1,
    "Hawaii, University of": 76,
    "Hofstra University": 103,
    "Houston, University of": 61,
    "Howard University": 54,
    "Idaho, University of": 121,
    "Illinois, University of": 41,
    "Illinois-Chicago, University of": 112,
    "Indiana University-Bloomington": 34,
    "Indiana University-Indianapolis": 85,
    "Inter American University of Puerto Rico": 184,
    "Iowa, University of": 34,
    "Kansas, The University of": 61,
    "Kentucky, University of": 70,
    "Lewis & Clark Law School": 85,
    "Liberty University": 184,
    "Lincoln Memorial University": 184,
    "Louisiana State University": 97,
    "Louisville, University of": 103,
    "Loyola Marymount University-Los Angeles": 76,
    "Loyola University-Chicago": 70,
    "Loyola University-New Orleans": 103,
    "Maine, University of": 112,
    "Marquette University": 85,
    "Maryland, University of": 46,
    "Massachusetts/Dartmouth, University of": 162,
    "Memphis, The University of": 144,
    "Mercer University": 121,
    "Miami, University of": 61,
    "Michigan State University": 76,
    "Michigan, University of": 9,
    "Minnesota, University of": 18,
    "Mississippi College": 171,
    "Mississippi, The University of": 103,
    "Missouri, University of": 76,
    "Missouri-Kansas City, University of": 112,
    "Mitchell/Hamline School of Law": 121,
    "Montana, University of": 138,
    "Nebraska, University of": 85,
    "Nevada-Las Vegas, University of": 61,
    "New England Law/Boston": 171,
    "New Hampshire, University of": 121,
    "New Mexico, The University of": 97,
    "New York Law School": 121,
    "New York University": 6,
    "North Carolina Central University": 154,
    "North Carolina, University of": 25,
    "North Dakota, University of": 144,
    "North Texas at Dallas, University of": 162,
    "Northeastern University": 70,
    "Northern Illinois University": 144,
    "Northern Kentucky University": 162,
    "Northwestern University": 15,
    "Notre Dame, University of": 18,
    "Nova Southeastern University": 171,
    "Ohio Northern University": 171,
    # "Ohio State University, The" — removed; Excel uses "The Ohio State University"
    "Oklahoma City University": 171,
    "Oklahoma, University of": 76,
    "Oregon, University of": 54,
    "Pace University": 121,
    "Pacific, University of the": 112,
    "Penn State Dickinson Law": 85,
    "Penn State University Park": 85,
    "Pennsylvania, University of": 9,
    "Pepperdine University": 61,
    "Pittsburgh, University of": 76,
    "Pontifical Catholic University of Puerto Rico": 180,
    "Puerto Rico, University of": 162,
    "Quinnipiac University": 121,
    "Regent University": 180,
    "Richmond, University of": 61,
    "Roger Williams University": 154,
    "Rutgers University": 61,
    "Saint Louis University": 85,
    "Samford University": 154,
    "San Diego, University of": 51,
    "San Francisco, University of": 138,
    "Santa Clara University": 76,
    "Seattle University": 76,
    "Seton Hall University": 85,
    "South Carolina, University of": 70,
    "South Dakota, University of": 144,
    "South Texas College of Law Houston": 154,
    "Southern California, University of": 18,
    "Southern Illinois University": 154,
    "Southern Methodist University": 54,
    "Southern University": 162,
    "Southwestern Law School": 144,
    "St. John's University": 97,
    "St. Mary's University": 144,
    "St. Thomas University (Miami)": 184,
    "St. Thomas, (Minneapolis) University of": 112,
    "Stanford University": 1,
    "Stetson University": 112,
    "Suffolk University": 112,
    "Syracuse University": 97,
    "Temple University": 54,
    "Tennessee, University of": 61,
    "Texas A&M University": 46,
    "Texas Southern University": 171,
    "Texas Tech University": 121,
    "Texas, University of": 15,
    "The Ohio State University": 30,
    "Toledo, The University of": 154,
    "Touro University": 162,
    "Tulane University": 46,
    "Tulsa, The University of": 121,
    "Utah, The University of": 41,
    "Vanderbilt University": 17,
    "Vermont Law School": 121,
    "Villanova University": 61,
    "Virginia, University of": 6,
    "Wake Forest University": 41,
    "Washburn University": 121,
    "Washington University (St. Louis)": 18,
    "Washington and Lee University": 41,
    "Washington, University of": 34,
    "Wayne State University": 85,
    "West Virginia University": 138,
    "Western New England University": 180,
    "Western State, Westcliff University": 184,
    "Widener University Commonwealth Law School": 154,
    "Widener University Delaware Law School": 138,
    "Willamette University": 121,
    "William & Mary": 30,
    "Wisconsin, University of": 25,
    "Wyoming, University of": 121,
    "Yale University": 4,
}
